# Generated by Django 3.2.3 on 2021-05-24 03:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('page_title', models.TextField(help_text='Title of the page as the public would see it.', max_length=300)),
                ('main_content', wagtail.core.fields.StreamField([('Question', wagtail.core.blocks.StructBlock([('question', wagtail.core.blocks.CharBlock(help_text="The question you'd like to answer.", max_length=255)), ('answer', wagtail.core.blocks.TextBlock(help_text='The answer to the provided question.'))]))])),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
