# Generated by Django 3.2.3 on 2021-05-23 22:39

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionspage',
            name='main_content',
            field=wagtail.core.fields.StreamField([('Attraction', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Main Image for the attraction')), ('title', wagtail.core.blocks.CharBlock(help_text='Title of the attraction.', max_length=60)), ('text', wagtail.core.blocks.TextBlock(help_text='Desciption of the attraction.'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attractionspage',
            name='page_title',
            field=models.CharField(default='title', help_text='Main title for the page.', max_length=200),
            preserve_default=False,
        ),
    ]
