# Generated by Django 3.2.3 on 2021-05-23 22:44

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20210523_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionspage',
            name='main_content',
            field=wagtail.core.fields.StreamField([('Attraction', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Main Image for the attraction')), ('title', wagtail.core.blocks.CharBlock(help_text='Title of the attraction.', max_length=60)), ('text', wagtail.core.blocks.TextBlock(help_text='Desciption of the attraction.')), ('link', wagtail.core.blocks.CharBlock(blank=True, help_text='Link to learn more about the attraction.', max_length=250))]))], blank=True, null=True),
        ),
    ]
