# Generated by Django 3.1.11 on 2021-05-30 02:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210529_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenitiespage',
            name='main_content',
            field=wagtail.core.fields.StreamField([('Amenity', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Image displayed on the side for the amenity.', required=False)), ('title', wagtail.core.blocks.CharBlock(help_text='Title of the amenity.', max_length=60)), ('text', wagtail.core.blocks.TextBlock(help_text='Desciption of the amenity.'))]))], blank=True, null=True),
        ),
    ]
