# Generated by Django 3.2.9 on 2021-11-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210529_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenitiespage',
            old_name='main_content',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='amenitiespage',
            old_name='section_body',
            new_name='amenities_carousel',
        ),
    ]
