# Generated by Django 3.1 on 2020-10-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_section_text', models.CharField(blank=True, help_text='Main Text displayed in the hero section over the background video.', max_length=255)),
                ('hero_section_subtitle_text', models.TextField(blank=True, help_text='Subtitle Text displayed in the hero section over the background video.', max_length=350)),
                ('cta_button_text', models.CharField(blank=True, default='Learn More', help_text='Call-To-Action Button Text', max_length=20)),
                ('cta_button_link', models.ForeignKey(blank=True, help_text='Internal page link to send the user to when clicking CTA button.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
