# Generated by Django 3.2.9 on 2021-11-28 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0002_homepage_hero_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='The daily rate for a single site.', max_digits=6)),
                ('weekly_rate', models.DecimalField(decimal_places=2, help_text='The weekly rate for a single site.', max_digits=6)),
                ('monthly_rate', models.DecimalField(decimal_places=2, help_text='The monthly rate for a single site not including electric.', max_digits=6)),
                ('monthly_rate_all_included', models.DecimalField(decimal_places=2, help_text='The monthly rate for a single site including electricity.', max_digits=6)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
