# Generated by Django 3.2.9 on 2021-11-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, help_text='The daily rate for a single site.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, help_text='The monthly rate for a single site not including electric.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='monthly_rate_all_included',
            field=models.DecimalField(decimal_places=2, help_text='The monthly rate for a single site including electricity.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, help_text='The weekly rate for a single site.', max_digits=6, null=True),
        ),
    ]
